---
defaultBaseImageVersion: latest
properties:
- name: HELM_VERSION
  value: ''
  type: text
- name: IBM_CLOUD_API_KEY
  value: ${API_KEY}
  type: secure
- name: COMMONS_HOSTED_REGION
  value: ${COMMONS_HOSTED_REGION}
  type: text
  default: "https://raw.githubusercontent.com/open-toolchain/commons/master"
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${GIT_BRANCH}
    service: ${GIT_REPO}
  triggers:
  - type: commit
  properties:
  jobs:
  - name: Build umbrella chart
    type: builder
    build_type: cr
    artifact_dir: output
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${APP_NAME}
    script: |
      #!/bin/bash
      #set -x
      cp -R -n ./ $ARCHIVE_DIR/ || true
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/fetch_git_creds.sh")
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/build_umbrella_chart.sh")
- name: STAGING
  inputs:
  - type: job
    stage: BUILD
    job: Build umbrella chart
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${STAGING_CLUSTER_NAMESPACE}
    type: text
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: LOGICAL_ENV_NAME
    value: STAGING
    type: text
  - name: HOST
    value: ondemand.saucelabs.com
    type: text
  - name: PORT
    value: '80'
    type: text
  - name: SERVICE_ID
    value: undefined
    type: text
  - name: POLICY_NAME_FORMAT
    value: ${POLICY_NAME_FORMAT}
    type: text
  jobs:
  - name: Staging gate
    type: tester
    script: |-
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/check_umbrella_gate.sh")
  - name: Config cluster
    type: deployer
    target:
      region_id: ${STAGING_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${STAGING_RESOURCE_GROUP}
      kubernetes_cluster: ${STAGING_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/check_predeploy_helm.sh")
  - name: Config service
    type: deployer
    target:
      api_key: ${API_KEY}
      region_id: ${STAGING_REGION_ID}
      resource_group: ${STAGING_RESOURCE_GROUP}
      kubernetes_cluster: ${STAGING_CLUSTER_NAME}
    script: |
      #!/bin/bash
      INSTANCE_NAME=myMicroservicesCloudant
      SERVICE_NAME=cloudantnosqldb
      SERVICE_PLAN=lite
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/cluster_config_service.sh")      
  - name: Deploy umbrella chart
    type: deployer
    target:
      region_id: ${STAGING_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${STAGING_RESOURCE_GROUP}
      kubernetes_cluster: ${STAGING_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/deploy_umbrella_chart.sh")
  - name: Sauce Labs Tests
    type: tester
    extension_id: ibm.devops.services.pipeline.saucelabs
    services:
      - ${SAUCE_LABS}
    DL_ASSETS: 'false'
    SELECT_CMD: custom
    COMMAND: |-
      #!/bin/bash
      # set -x
      if [ -f ./tests/run-tests.sh ]; then
        source ./tests/run-tests.sh
      else
        echo "Test runner script not found: ./tests/run-tests.sh"
      fi
    enable_tests: true
    test_file_pattern: '*.xml'
- name: PROD
  inputs:
  - type: job
    stage: BUILD
    job: Build umbrella chart
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: LOGICAL_ENV_NAME
    value: PROD
    type: text
  - name: SERVICE_ID
    value: undefined
    type: text
  - name: POLICY_NAME_FORMAT
    value: ${POLICY_NAME_FORMAT}
    type: text    
  jobs:
  - name: Production gate
    type: tester
    script: |-
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/check_umbrella_gate.sh")
  - name: Config cluster
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${PROD_RESOURCE_GROUP}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/check_predeploy_helm.sh")
  - name: Config service
    type: deployer
    target:
      api_key: ${API_KEY}
      region_id: ${PROD_REGION_ID}
      resource_group: ${PROD_RESOURCE_GROUP}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      INSTANCE_NAME=myMicroservicesCloudant
      SERVICE_NAME=cloudantnosqldb
      SERVICE_PLAN=lite
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/cluster_config_service.sh")
  - name: Deploy umbrella chart
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${PROD_RESOURCE_GROUP}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #set -x
      source <(curl -sSL "${COMMONS_HOSTED_REGION}/scripts/deploy_umbrella_chart.sh")
